# Generated by Django 6.1 on 2026-08-16 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('шт.', 'шт.'), ('упак.', 'упак.'), ('компл.', 'компл.'), ('м', 'м'), ('м²', 'м²'), ('м³', 'м³'), ('кг', 'кг'), ('т', 'т'), ('л', 'л'), ('м.п.', 'м.п.'), ('рул.', 'рул.'), ('лист', 'лист'), ('пара', 'пара'), ('секция', 'секция'), ('банка', 'банка'), ('ведро', 'ведро'), ('другое', 'другое')], default='шт.', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Получен'), ('checking', 'На проверке'), ('warning', 'Есть замечания'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='received', max_length=20)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Паспорт'), ('certificate', 'Сертификат'), ('declaration', 'Декларация'), ('quality', 'Сертификат качества'), ('protocol', 'Протокол испытаний'), ('photo', 'Фото'), ('other', 'Другой документ')], default='other', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='material_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.object')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_codes', to='core.position')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='project_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.projectcode'),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='core.supplier'),
        ),
    ]
