# Generated by Django 6.1 on 2026-08-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='note_level',
            field=models.CharField(choices=[('none', 'Нет замечаний'), ('low', 'Лёгкое'), ('medium', 'Среднее'), ('critical', 'Критическое')], default='none', max_length=20),
        ),
    ]
