# Generated by Django 6.1 on 2026-08-16 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_material_note_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Разработка'), ('signed', 'Подписан')], default='draft', max_length=20)),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='material_acts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='core.material')),
            ],
        ),
    ]
