# Generated by Django 6.1 on 2026-08-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_materialact'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialact',
            name='accompanying_documents',
            field=models.TextField(blank=True, verbose_name='Сопроводительная документация'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='compliance_result',
            field=models.CharField(blank=True, max_length=50, verbose_name='Соответствие'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='conclusion',
            field=models.TextField(blank=True, verbose_name='Заключение'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='construction_section',
            field=models.CharField(blank=True, max_length=500, verbose_name='Участок / привязка / км / ПК'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='contractor',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подрядчик'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='contractor_position',
            field=models.CharField(blank=True, max_length=300, verbose_name='Должность представителя подрядчика'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='contractor_representative',
            field=models.CharField(blank=True, max_length=300, verbose_name='Представитель подрядчика'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='contractor_signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписи подрядчика'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='customer',
            field=models.CharField(blank=True, max_length=300, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='customer_position',
            field=models.CharField(blank=True, max_length=300, verbose_name='Должность представителя заказчика'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='customer_representative',
            field=models.CharField(blank=True, max_length=300, verbose_name='Представитель заказчика'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='customer_signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписи заказчика'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='documents_complete',
            field=models.BooleanField(default=True, verbose_name='Документация в полном комплекте'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='geometric_dimensions',
            field=models.TextField(blank=True, verbose_name='Геометрические размеры'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='inspection_type',
            field=models.CharField(choices=[('continuous', 'Сплошной'), ('selective', 'Выборочный'), ('sample', 'С выборкой')], default='continuous', max_length=30, verbose_name='Вид проверки'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='marking',
            field=models.TextField(blank=True, verbose_name='Маркировка'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='mechanical_properties',
            field=models.TextField(blank=True, verbose_name='Характеристики механических свойств'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='mechanical_properties_result',
            field=models.TextField(blank=True, verbose_name='Результат проверки механических свойств'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='object_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='position_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='product_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Наименование изделий'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='product_type',
            field=models.CharField(blank=True, max_length=500, verbose_name='Вид изделий'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='project_code',
            field=models.CharField(blank=True, max_length=300, verbose_name='Шифр проекта'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='project_document',
            field=models.CharField(blank=True, max_length=500, verbose_name='Проект / чертёж'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='project_document_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проекта / чертежа'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='project_requirements',
            field=models.TextField(blank=True, verbose_name='Требования проекта'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='technical_conditions',
            field=models.TextField(blank=True, verbose_name='Технические условия'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='technical_requirements',
            field=models.TextField(blank=True, verbose_name='Технические условия'),
        ),
        migrations.AddField(
            model_name='materialact',
            name='working_drawings',
            field=models.CharField(blank=True, max_length=500, verbose_name='Рабочие чертежи'),
        ),
        migrations.AlterField(
            model_name='materialact',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата акта'),
        ),
        migrations.AlterField(
            model_name='materialact',
            name='number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер акта'),
        ),
        migrations.AlterField(
            model_name='materialact',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to='material_acts/', verbose_name='Подписанный АоРПИ'),
        ),
        migrations.AlterField(
            model_name='materialact',
            name='status',
            field=models.CharField(choices=[('draft', 'Разработка'), ('signed', 'Подписан')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
