# Generated by Django 6.1 on 2026-08-17 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_materialact_accompanying_documents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('vkh_engineer', 'Инженер ВХК'), ('lead_vkh_engineer', 'Ведущий инженер ВХК'), ('pto_engineer', 'Инженер ПТО'), ('management', 'Руководство'), ('guest', 'Гость')], default='guest', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
