# Generated by Django 6.1 on 2026-08-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_objects',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='core.object'),
        ),
    ]
