# Generated by Django 6.1 on 2026-08-17 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_allowed_objects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allowed_objects',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='core.object', verbose_name='Доступные объекты'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('vkh_engineer', 'Инженер ВХК'), ('lead_vkh_engineer', 'Ведущий инженер ВХК'), ('pto_engineer', 'Инженер ПТО'), ('management', 'Руководство'), ('guest', 'Гость')], default='guest', max_length=30, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
