# Generated by Django 6.1 on 2026-08-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('vkh_engineer', 'Инженер ВК'), ('lead_vkh_engineer', 'Ведущий инженер ВК'), ('pto_engineer', 'Инженер ПТО'), ('management', 'Руководство'), ('guest', 'Гость')], default='guest', max_length=30, verbose_name='Роль'),
        ),
    ]
