# Generated by Django 6.1.1 on 2026-09-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('designation', models.CharField(max_length=100, unique=True, verbose_name='Обозначение')),
                ('document_type', models.CharField(choices=[('gost', 'ГОСТ'), ('gost_r', 'ГОСТ Р'), ('sp', 'СП'), ('snip', 'СНиП'), ('pue', 'ПУЭ'), ('sanpin', 'СанПиН'), ('other', 'Другой документ')], default='gost', max_length=20, verbose_name='Тип документа')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='normative_documents/', verbose_name='Файл документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
                'ordering': ['document_type', 'designation'],
            },
        ),
    ]
